### ISSUE TITLE
Don't works with my LDAP server.

### ISSUE THREAD

**Issue by shogogg** [jirutka/ssh-getkey-ldap#1]
#### OS
- **client:** Alpine Linux 3.4
- **server:** CentOS 5.11

#### Version
- **client:** ssh-getkey-ldap-0.1.1-r0
- **server:** openldap-2.3.43-29.el5_11

#### Current behavior
An error occurred.
```
stack traceback:
	[C]: in function 'concat'
	/usr/bin/ssh-getkey-ldap:107: in main chunk
	[C]: ?
```

#### Expected behavior
Display public key.

#### My solution
I had try to fix it, so I edit a line 107

```
print(table.concat(pubkeys, '\n'))
```

to

```
print(attrs[cfg.pubkey_attr])
```

Then, it works. But I don't know much about Lua and lualdap, so I don't understand why it works and why current version not works.

Could you fix this?

**Comment by jirutka** [comment]
It seems that `attrs[cfg.pubkey_attr]` is a string instead of table (list) of strings in your case. What schema for `sshPublicKey` do you use? [openssh-lpk.schema](https://raw.githubusercontent.com/jirutka/ssh-ldap-pubkey/v0.4.1/etc/openssh-lpk.schema) or some custom? Can you add multiple keys for one user?

**Comment by shogogg** [comment]
@jirutka Sorry for my late reply.

> Can you add multiple keys for one user?

No, I can't.

> What schema for sshPublicKey do you use? 

I'm using the schema below:
```
#
# LDAP Public Key Patch schema for use with openssh-ldappubkey
# Author: Eric AUGE <eau@phear.org>
#
# Based on the proposal of : Mark Ruijter
#


# octetString SYNTAX
attributetype ( 1.3.6.1.4.1.24552.500.1.1.1.13 NAME 'sshPublicKey'
        DESC 'MANDATORY: OpenSSH Public key'
        EQUALITY octetStringMatch
        SYNTAX 1.3.6.1.4.1.1466.115.121.1.40 )

# printableString SYNTAX yes|no
objectclass ( 1.3.6.1.4.1.24552.500.1.1.2.0 NAME 'ldapPublicKey' SUP top AUXILIARY
        DESC 'MANDATORY: OpenSSH LPK objectclass'
        MAY ( sshPublicKey $ uid )
        )
```

It is similar to [openssh-lpk.schema](https://raw.githubusercontent.com/jirutka/ssh-ldap-pubkey/v0.4.1/etc/openssh-lpk.schema), but there is some little differents (e.g. `MAY ( sshPublicKey $ uid )` and `MUST ( sshPublicKey $ uid )`), and I don't know why.

But other clients (e.g. openssh-ldap package in CentOS) are works fine with this schema.

I would be happy if you could support this case.
